[workspace]
members = [
    "console_app",
    "raytracer_weekend_lib",
    "discovery_app",
    "discovery_app/testsuite",
    "discovery_host_receiver",
]

[profile.release.package.raytracer_weekend_console]
debug = true
